/*{CA:PACKAGE_IMPORTS:START}*/
/*{CA:PACKAGE_IMPORTS:END}*/

/*{CA:PROJECT_IMPORTS:START}*/
/*{CA:PROJECT_IMPORTS:END}*/

export interface CategoryDto {
    id?: string;
    description: string;

    /*{CA:INTERFACE_ATTRIBUTES:START}*/
    /*{CA:INTERFACE_ATTRIBUTES:END}*/
}

/*{CA:FILE_CONTENTS:START}*/
/*{CA:FILE_CONTENTS:END}*/
